### ISSUE TITLE
Non-issue: template credits

### ISSUE THREAD

**Issue by ovasquez** [code-beans/UnityFX#1]
I noticed that you based your template on my implementation of DocFX Material, I'm flattered that someone liked what I made, it would be nice if you could add a reference to my repo, something like "Based of DocFX Material https://ovasquez.github.io/docfx-material/" or something like that, to keep the spirit of community alive :)

Cheers!
Oscar

**Comment by code-beans** [comment]
Hey Oscar,
looking at your Material theme I must have missed that. I will add it to the readme
